Add Telegram support, colors and puzzle solving timestamps
tofran/advent-of-code-leaderboard-notifier pull request #2
Opened 2023-12-03 16:10 UTC by iburakov

Hi there! Thanks for sharing this code, it was very helpful. 

I've done some further work on it for my own requirements and created a [fork](https://github.com/iburakov/advent-of-code-leaderboard-notifier-telegram) as a separate repo with its own builds for the time being. 

Just suggesting you to take a look, because I have nothing against merging this work back to yours (if you consider it reasonable, of course).

I've simplified writing custom webhook senders and implemented one for Telegram. I've also added colors and event times to notifications, so now they look like this:

<img src='https://github.com/iburakov/advent-of-code-leaderboard-notifier-telegram/assets/5229130/83e0aad9-1b2f-4453-945c-2ae96b83b091' height='300'>

The formatting part is pretty opinionated, yeah. If you don't like it, a way to please everyone would be to accept pattern str in another env var and do a `.format(day=..., part=..., part_emoji=...)`. So, your format becomes `NOTIFICATION_PATTERN="{member} solved day {day} part {part}"`, mine becomes `NOTIFICATION_PATTERN="Day {day}: {member} got {part_emoji} at {when}"`, users can come up with every other thing they like, etc.

So, if you're open to merging it, let me know, because (at least) a README needs some changes for it to be mergeable :) Otherwise feel free to close this PR.

2023-12-03 22:34 UTC, tofran commented
@iburakov Thank you very much for all the effort! I love it, and thank you for preserving the code-style.

I will have a better look later. But the only thing I will point outright now is the emoji, the colored circle is not very representative - at least in my opinion. I would change it to one of the following (1st, 2nd puzzle):

- ⭐, 🌟
- 🌲, 🎄
- 🌱, 🌲/🎄

2023-12-03 22:50 UTC, tofran commented
Woops the action failed because it is directly pushing the image, I would imagine it would do some sort of linting. Please ignore it. I will fix it in another PR

2023-12-04 00:21 UTC, tofran requested changes
I like it! Thank you for the logging addition.

What do you think of these changes?:

2023-12-04 00:21 UTC, tofran commented on webhook_senders.py
> +class WebhookSender(ABC):
I would call this `BaseNotificationSender`.

2023-12-04 00:21 UTC, tofran commented on webhook_senders.py
> +class DefaultSender(WebhookSender):
.... and this `WebhookSender`

2023-12-04 00:21 UTC, tofran commented on README.md
> +This is a fork of [tofran/advent-of-code-leaderboard-notifier](https://github.com/tofran/advent-of-code-leaderboard-notifier) that:
As you mentioned this needs work, if you wish, I can help with that. Feel free to enable author contribution permission.

2023-12-04 00:21 UTC, tofran commented on README.md
> +- `WEBHOOK_TELEGRAM_CHAT_ID`: comma-separated list of chat IDs to send notifications to. See [Telegram docs](https://core.telegram.org/bots/api#sendmessage) for more info. You can find them using bot
Please prefix it with an `S` for plural: `WEBHOOK_TELEGRAM_CHAT_IDS`

2023-12-04 07:37 UTC, iburakov commented
That's nice to hear you like it, thanks! Great idea about distinct patterns for both notifications, that'll be much more flexible, indeed.

Here are my plans for the next few hours:
- address requested changes
- implement getting two notification patterns from the env
- ensure the code passes the linting you've pushed recently

I'll write here when I'm done. You should have the edit rights, feel free to change anything for the merge. ~Please, use the new [to-be-merged-back](https://github.com/iburakov/advent-of-code-leaderboard-notifier-telegram/tree/to-be-merged-back) branch.~ Nevermind, use `main` :) Apparently I can't change the source branch of this PR, so we're stuck on main here.

2023-12-04 07:41 UTC, iburakov commented on webhook_senders.py
> +class WebhookSender(ABC):
Yeah, that generalizes the concept for even more applications. Ok, let's do it, and I'll try to make sense of everything related like renaming the `WEBHOOK_SENDER` env var to `NOTIFICATION_SENDER` as well.

2023-12-04 07:42 UTC, iburakov commented on webhook_senders.py
> +class DefaultSender(WebhookSender):
yep, makes sense, given the change above

2023-12-04 07:44 UTC, iburakov commented on README.md
> +This is a fork of [tofran/advent-of-code-leaderboard-notifier](https://github.com/tofran/advent-of-code-leaderboard-notifier) that:
yeah, you should have the rights, go ahead :)

2023-12-04 07:45 UTC, iburakov commented on README.md
> +- `WEBHOOK_TELEGRAM_CHAT_ID`: comma-separated list of chat IDs to send notifications to. See [Telegram docs](https://core.telegram.org/bots/api#sendmessage) for more info. You can find them using bot
right, thanks

2023-12-04 11:36 UTC, iburakov commented
So, after considering a few ways to enable customizing notification patterns and emojis, that's what I suggest as a flexible-yet-convenient way: 

```python
NOTIFICATION_PATTERN_EMOJIS = os.getenv("NOTIFICATION_PATTERN_EMOJIS", "🌱🎄")
NOTIFICATION_PATTERN = os.getenv(
    "NOTIFICATION_PATTERN", "Day {day}: {member} got {part_emoji} at {when}"
)
NOTIFICATION_2_PATTERN = os.getenv("NOTIFICATION_2_PATTERN", NOTIFICATION_PATTERN)
```

It seems to cover basically all discussed needs with minimal effort. Override only `NOTIFICATION_PATTERN_EMOJIS` if you need to change just the emojis, override the whole `NOTIFICATION_PATTERN` if you need to translate it, and, optionally, override `NOTIFICATION_2_PATTERN` if it must be structurally different from the first one.

2023-12-04 12:26 UTC, iburakov commented
A friend of mine also suggested to display the time as "[d] hh:mm:ss" since moment of corresponding puzzle publication. I tried it, it's arguably more convenient than absolute :mm:ss.

```
Day 4: Alice got 🌱 after 00:11:16
Day 4: Alice got 🎄 after 00:24:34
Day 4: Bob got 🌱 after 00:58:26
Day 4: Bob got 🎄 after 01:19:11
```

Implemented it as an `after` notification pattern key. How that sounds?  FYI, I've updated the default `NOTIFICATION_PATTERN` to this.

2023-12-04 13:39 UTC, iburakov commented
Done, fixed the lint CI workflow as well. Treat all changes here as suggestions that seemed reasonable to me.

Leaving everything up to you now. You should have the edit rights, so change anything as you wish, especially README.

2023-12-05 01:49 UTC, tofran approved these changes
I think it looks great. Thank you for all the work.
Also, sorry for the broken github workflow. Should be working now (at least green on this side).

Can you spot anything or can I merge?

2023-12-05 09:14 UTC, iburakov commented
LGTM! Glad this worked.

2023-12-05 09:49 UTC, merged

2023-12-05 09:57 UTC, tofran commented
@iburakov right now should be available at `ghcr.io/tofran/advent-of-code-leaderboard-notifier:main`
I will do a release later.

2023-12-05 10:19 UTC, iburakov commented
Good, thanks. Also spotted a couple of typos at the second glance:

---
https://github.com/tofran/advent-of-code-leaderboard-notifier/blob/e3cf8204e2b3ac1a7c9aebaabfb9050ef9e495d1/README.md?plain=1#L86
2dn -> 2nd

---
https://github.com/tofran/advent-of-code-leaderboard-notifier/blob/e3cf8204e2b3ac1a7c9aebaabfb9050ef9e495d1/README.md?plain=1#L5
"group of friends, or co-workers" - extra comma, perhaps

2023-12-07 21:53 UTC, tofran commented
Thank you. Fixed those and released the new version: [v1.3.0](https://github.com/tofran/advent-of-code-leaderboard-notifier/releases/tag/v1.3.0)